name: example
description: A simple command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  built_collection: ^5.0.0
  glina:
    path: ../glina

dev_dependencies:
  pedantic: ^1.9.0
  build_runner: ^1.12.2
  glina_generator:
    path: ../glina_generator
