builders:
  glina:
    import: "package:glina_generator/builder.dart"
    builder_factories: ["glina"]
    build_extensions: {".dart": [".glina.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]