name: glina_generator
description: The generator for glina.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  source_gen: ^1.0.0
  build: ^2.0.0
  analyzer: ^1.4.0
  glina:
    path: ../glina

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
